version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing SonarScanner CLI...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-* sonar-scanner
      - export PATH=$PATH:$(pwd)/sonar-scanner/bin

  build:
    commands:
      - echo Running SonarCloud analysis...
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN

env:
  secrets-manager:
    SONAR_TOKEN: sonarcloud-token